function MyAccountInfo(){
    return(
        <div>
            <div>
                <p>アカウント情報</p>
            </div>
            <div>
                <p>プロフィール情報</p>
                <div>
                    <div>
                        <p>氏名</p>
                        <p>{}</p>
                    </div>
                    <div>
                        <p>生年月日</p>
                        <p>{}</p>
                    </div>
                    <div>
                        <p>メールアドレス</p>
                    </div>
                </div>
                <p>通知設定</p>
                <div></div>
                <p>支払い情報</p>
                <div></div>
            </div>
        </div>
    )
}
export default MyAccountInfo;